name: mlops

on:
  push:
permissions:
      id-token: write
      contents: read
jobs:
  s3ls:
    runs-on: ubuntu-latest
    
    steps:
      - uses: aws-actions/configure-aws-credentials@main
        with:
          aws-region: 'ap-northeast-1' 
          role-to-assume: 'arn:aws:iam::205474062727:role/mlops'


      - run: aws s3 ls s3://mlops-s3-a

